### ISSUE TITLE
upgrade splunk version on running container

### ISSUE THREAD

**Issue by sarit12** [splunk/docker-splunk#391] opened 2020-07-12 12:45 UTC
Hello
i had splunk version 7.2.6 and i wanted to upgrade to 8.0.2
the container already had splunk running and after upgrading im getting this error:

> > TASK [splunk_common : Check for existing splunk secret] ************************
> fatal: [localhost]: FAILED! => {
>     "changed": false
> }
> 
> MSG:
> 
> Permission denied
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0 

when running splunk version 8.0.2 on "clean" environment it is working fine.

how can i fix this error ?

thanks

**Comment by nwang92** [comment] 2020-07-15 01:53
Are you using the image through Docker/Swarm or Kubernetes?

It seems like what's happening is when named volumes are mounted on the new container they appear to be owned by `ansible` instead of `splunk`. This might be a side-effect of the default `ansible` user on the container? But knowing which orchestrator you're using would help in providing the appropriate solution.

**Comment by sarit12** [comment] 2020-07-15 08:20
Hello.
thanks for your answer
i'm using image through Docker but running with Kubernetese.

**Comment by nwang92** [comment] 2020-07-15 16:49
Perfect, in that case you made need to add the proper `securityContext` so mounted volumes are attached with the correct permissions. For instance:
```
apiVersion: v1
kind: Pod
metadata:
  name: splunk
spec:
  securityContext:
    fsGroup: 41812 # this maps to the splunk user in these containers
...
```

Alternatively, you can add an `initContainer` to perform the chown:
```
initContainers:
- name: take-etc-dir-ownership
  image: alpine:3.6
  command:
  - chown
  - -R  
  - 41812:41812
  - /opt/splunk/etc
  volumeMounts:
  - name: splunk-etc
    mountPath: /opt/splunk/etc
```

**Comment by sarit12** [comment] 2020-07-16 11:19
Thanks !
i used the first option and now im getting this error:

FAILED - RETRYING: Test basic https endpoint (45 retries left).
TASK [splunk_search_head : Check Splunk instance is running] *******************
fatal: [localhost]: FAILED! => {
    "attempts": 60, 
    "changed": false, 
    "content": "", 
    "elapsed": 0, 
    "redirected": false, 
    "status": -1, 
    "url": "http://splunk-master:8089/services/server/info?output_mode=json"
}

MSG:

Status code was -1 and not [200]: Connection failure: [Errno 104] Connection reset by peer
...ignoring

**Comment by nwang92** [comment] 2020-07-17 16:28
This seemed like an error that was fixed by https://github.com/splunk/splunk-ansible/pull/507, but actually the `Connection reset` may be a legitimate failure. This is generally caused by Splunk failing to start, even though the command `./bin/splunk start` might have appeared to succeed and exit cleanly. 

Going to see if I can repro this in a k8s environment. Are you running the image with any of the feature flags/non-default settings?

**Comment by sarit12** [comment] 2020-07-17 17:07
Hey
I really appreciate your help!

Im not sure i understand your question:)

**Comment by nwang92** [comment] 2020-07-17 23:33
Should've been more specific :P Could you show me your kube yaml file for how the container is deployed? And if you have a `default.yml` configmap/secret attached, could you share that as well?

**Comment by sarit12** [comment] 2020-07-18 08:02
are you referring to this ?
```
`splunk-chart:
  namespace: dev-aviation-02  
  persistence:
    search:
      dataSize: 50Gi
      configSize: 10Gi
    master:
      dataSize: 50Gi
      configSize: 10Gi
    indexer:
      dataSize: 250Gi
      configSize: 10Gi
  app:
    customerName: argus
  configs:
    enabled: true
    ## The image must contain 'indexer','master', and 'search' dirs in /data
    image:
      repository: gcr.io/argussec1/splunk-aviation-configs
      tag: 2.19.0-alpha.ff3cdd3
    env:
      - name: SPLUNK_BEFORE_START_CMD
        value: sudo rm /opt/splunk/var/lib/splunk/kvstore/mongo/mongod.lock

  resources:
    requests:
      memory: 4Gi
      cpu: 1
    limits:
      memory: 8Gi
      cpu: 4

  app:
    customerName: argus
  
  # default configuration loaded by splunk, exposed by nginx
  splunkDefaults:
    defaultYml:
      ansible_post_tasks: null
      ansible_pre_tasks: null
      config:
        baked: default.yml
        defaults_dir: /tmp/defaults
        env:
          headers: null
          var: SPLUNK_DEFAULTS_URL
          verify: true
        host:
          headers: null
          url: null
          verify: true
        max_delay: 60
        max_retries: 3
        max_timeout: 1200
      hide_password: false
      retry_num: 50
      shc_bootstrap_delay: 30
      splunk:
        admin_user: admin
        allow_upgrade: true
        app_paths:
          default: /opt/splunaviationtc/apps
          deployment: /opt/spaviationk/etc/deployment-apps
          httpinput: /opt/splaviation/etc/apps/splunk_httpinput
          idxc: /opt/splunk/eaviationmaster-apps
          shc: /opt/splunk/etaviationhcluster/apps
        enable_service: false
        exec: /opt/splunk/bin/splunk
        group: splunk
        hec_disabled: 0
        hec_enableSSL: 0
        hec_port: 8088
        hec_token: *********-****-****-*****-********
        home: /opt/splunk
        http_enableSSL: 0
        http_enableSSL_cert: null
        http_enableSSL_privKey: null
        http_enableSSL_privKey_password: null
        http_port: 8000
        idxc:
          enable: false
          label: idxc_label
          replication_factor: 3
          replication_port: 9887
          search_factor: 3
          secret: ********
        ignore_license: false
        license_download_dest: /tmp/splunk.lic
        nfr_license: /tmp/nfr_enterprise.lic
        opt: /opt
        password: "" #overriden in the environment variables
        pid: /opt/splunk/var/run/splunk/splunkd.pid
        s2s_enable: true
        s2s_port: 9997
        search_head_cluster_url: null
        secret: null
        shc:
          enable: false
          label: shc_label
          replication_factor: 3
          replication_port: 9887
          secret: ******
        smartstore: null
        svc_port: 8089
        tar_dir: splunk
        user: splunk
        wildcard_license: false
        conf:
          server:
            directory: /opt/splunk/etc/system/local
            content:
              clustering:
                summary_replication : true
      splunk_home_ownership_enforcement: true 
```     
`

**Comment by nwang92** [comment] 2020-07-22 18:51
That looks correct, I guess this is from some helm chart? I'm not too familiar with the origins of this helm chart, but I don't see anything wrong with the default.yml there. The app paths is incorrect, these should be prefixed with `/opt/splunk` instead of `/opt/splaviation`:
```
        app_paths:
          default: /opt/splunaviationtc/apps
          deployment: /opt/spaviationk/etc/deployment-apps
          httpinput: /opt/splaviation/etc/apps/splunk_httpinput
```
But that shouldn't be the cause of any errors.

So far I haven't had much success reproducing what you're seeing. From your previous error msg:
```
MSG:
Status code was -1 and not [200]: Connection failure: [Errno 104] Connection reset by peer
...ignoring
```
I'm wondering if this is benign - it does appear to ignore these errors, but I'm not sure if that's causing the pod to fail for you. Maybe try the 8.0.5 image tag just published this week to see if that fixes anything for you? The fix for this retry-loop was patched there, wondering if that would solve the problem.

**Comment by sarit12** [comment] 2020-07-22 19:08
thanks, i will give it a try

**Comment by sarit12** [comment] 2020-07-23 09:10
Hey
so i've upgraded the version to 8.0.5
now im facing few things:

1. i see that the new version of splunk creates 2 containers, search and bash. this is the way it should be ?
2. in the search container i got the error:

> WARNING: No password ENV var.  Stack may fail to provision if splunk.password is not set in ENV or a default.yml
> License not accepted, please ensure the environment variable SPLUNK_START_ARGS contains the '--accept-license' flag
> For example: docker run -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD splunk/splunk
> 
> For additional information and examples, see the help: docker run -it splunk/splunk help
> ERROR: Couldn't read "/opt/splunk/etc/splunk-launch.conf" -- maybe $SPLUNK_HOME or $SPLUNK_ETC is set wrong?
i run 

> sudo docker run -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD splunk/splunk

and got this :

> Unable to find image 'splunk/splunk:latest' locally
> latest: Pulling from splunk/splunk
> e96e3a1df3b2: Pull complete 
> 1b99828eddf5: Pull complete 
> 662b34e6b5a0: Pull complete 
> a172909b9b61: Pull complete 
> 0c252b4a69f1: Pull complete 
> b1b01777b24c: Pull complete 
> 2e796fd20b57: Pull complete 
> e71c6e0e4244: Pull complete 
> 8fcf64560b28: Pull complete 
> fd2d61617bea: Pull complete 
> 71e708e501fb: Pull complete 
> Digest: sha256:9a9d6bdcf23dc43267903b03877f41c4fc9416c782c4f64c5aa20213bdac4b9b
> Status: Downloaded newer image for splunk/splunk:latest
> WARNING: No password ENV var.  Stack may fail to provision if splunk.password is not set in ENV or a default.yml
> /usr/lib64/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
>   CryptographyDeprecationWarning,
> [WARNING]:  * Failed to parse /opt/ansible/inventory/environ.py with script
> plugin: Inventory script (/opt/ansible/inventory/environ.py) had an execution
> error: Traceback (most recent call last):   File
> "/opt/ansible/inventory/environ.py", line 764, in <module>     main()   File
> "/opt/ansible/inventory/environ.py", line 750, in main
> getSplunkInventory(inventory)   File "/opt/ansible/inventory/environ.py", line
> 95, in getSplunkInventory     inventory["all"]["vars"] = getDefaultVars()
> File "/opt/ansible/inventory/environ.py", line 115, in getDefaultVars
> getSecrets(defaultVars)   File "/opt/ansible/inventory/environ.py", line 362,
> in getSecrets     raise Exception("Splunk password must be supplied!")
> Exception: Splunk password must be supplied!
> [WARNING]:  * Failed to parse /opt/ansible/inventory/environ.py with ini
> plugin: /opt/ansible/inventory/environ.py:16: Expected key=value host variable
> assignment, got: __future__
> [WARNING]: Unable to parse /opt/ansible/inventory/environ.py as an inventory
> source
> [WARNING]: No inventory was parsed, only implicit localhost is available
> [WARNING]: provided hosts list is empty, only localhost is available. Note that
> the implicit localhost does not match 'all'
> 
> PLAY [Run default Splunk provisioning] *****************************************
> Thursday 23 July 2020  08:43:20 +0000 (0:00:00.207)       0:00:00.207 ********* 
> 
> TASK [Gathering Facts] *********************************************************
> ok: [localhost]
> Thursday 23 July 2020  08:43:23 +0000 (0:00:03.145)       0:00:03.353 ********* 
> Thursday 23 July 2020  08:43:24 +0000 (0:00:00.104)       0:00:03.457 ********* 
> Thursday 23 July 2020  08:43:24 +0000 (0:00:00.100)       0:00:03.558 ********* 
> Thursday 23 July 2020  08:43:24 +0000 (0:00:00.110)       0:00:03.669 ********* 
> 
> TASK [Check all instances for required restarts] *******************************
> fatal: [localhost]: FAILED! => {}
> 
> MSG:
> 
> The field 'become_user' has an invalid value, which includes an undefined variable. The error was: 'splunk' is undefined
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   
> 
> Thursday 23 July 2020  08:43:24 +0000 (0:00:00.065)       0:00:03.735 ********* 
> =============================================================================== 
> Gathering Facts --------------------------------------------------------- 3.15s
> Execute post-setup playbooks -------------------------------------------- 0.11s
> Execute pre-setup playbooks --------------------------------------------- 0.10s
> Provision role ---------------------------------------------------------- 0.10s
> Check all instances for required restarts ------------------------------- 0.07s
> ERROR: Couldn't read "/opt/splunk/etc/splunk-launch.conf" -- maybe $SPLUNK_HOME or $SPLUNK_ETC is set wrong?
> 

what can i do ?

**Comment by nwang92** [comment] 2020-07-23 17:02
> i see that the new version of splunk creates 2 containers, search and bash. this is the way it should be ?
This should not be the case - the `splunk/splunk:8.0.5` docker image is a self-contained unit. There must be something else launching the 2nd container in the pod?

> sudo docker run -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD splunk/splunk
The error here is you need to supply a password, but there's not one currently set (unless you ran something before this command). Per the [following guide](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file), you would either need to run:
```
export SPLUNK_PASSWORD=helloworld
sudo docker run -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD splunk/splunk:8.0.5
```
or alternatively
```
sudo docker run -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld splunk/splunk:8.0.5
```
otherwise no value gets passed into the password parameter.

**Comment by nwang92** [comment] 2020-07-31 16:20
Going to close this due to inactivity, but feel free to re-open or comment if you're still having issues.

**Closed as completed by nwang92** 2020-07-31 16:20 UTC
