### ISSUE TITLE
How do I access certain (all) files?

### ISSUE THREAD

**Issue by qwerty10110** [splunk/docker-splunk#420] opened 2020-09-11 19:10 UTC
When I shell into the container I can't access  /opt/splunk/var/run, even when I use `sudo cd run/`

`sudo: unable to send audit message: Operation not permitted`

Why is it that I can't access all directories, even while I'm a sudo user?

PS: I originally posted this in splunk-ansible.  But I figured since I'm using splunk in a docker/kubernetes context, that I should also ask here.

**Comment by nwang92** [comment] 2020-09-16 20:23
Duplicate of https://github.com/splunk/splunk-ansible/issues/539

**Closed as completed by nwang92** 2020-09-16 20:23 UTC
