### ISSUE TITLE
Volume mounting with Docker Compose 

### ISSUE THREAD

**Issue by kuroiokami** [splunk/docker-splunk#268] opened 2019-10-31 20:36 UTC
From command line, it works for the most part as you would expect. Loads the apps in the mounted volume. 
`-v /path/to/app:/opt/splunk/etc/apps/`

In docker compose if it put
`      volumes:
        - /path/to/app:/opt/splunk/etc/apps/`

For some reason when splunk is loading it seems like I doesn't see? the apps and doesn't load correctly. I think this user was describing the same issue here https://answers.splunk.com/answers/746703/splunk-docker-failing-when-specifying-volume-mount.html

How do I get this to work correctly?

**Comment by nwang92** [comment] 2019-11-01 04:40
Are you seeing exactly the same error message as described in that Splunk Answers post? Even if it's slightly different or if it's an ansible failure, can you add that to this post?

Additionally it would be helpful to have the full `docker-compose.yml` you're using just to make sure everything else is set as expected.

**Comment by kuroiokami** [comment] 2019-11-01 13:05
What is the best way to get the logs that you need. When I try to mount it in docker compose, the ansible script finishes but splunk doesn't even start. If I remove the volume declaration it atleast starts up clean.

**Comment by nwang92** [comment] 2019-11-01 22:06
I would create the containers via `docker run` or `docker-compose` and after the container fails to provision successfully, run a `docker logs <container-id/name>` to grab the output. Then drop it in a gist and send it to me.

**Comment by OllieJC** [comment] 2019-11-02 16:22
I've been trying to update my containers to `v8.0.0` but app volume mounting seems broken in recent versions.

Based on this documentation: https://splunk.github.io/docker-splunk/advanced/APP_INSTALL.html
I got the following to work (where `LOCAL-APP-FOLDER` is the local folder with `default` / `metadata` etc. in, and `APP-ID` is the same as the `LOCAL-APP-FOLDER` name and the `id` field in `app.conf`)
```
FROM splunk/splunk:8.0
COPY ./LOCAL-APP-FOLDER /tmp/APP-ID/
RUN cd /tmp/ && \
    tar -cvf /tmp/app.tar APP-ID/ && \
    gzip --no-name "/tmp/app.tar"
```
and adding an environment variable to my `docker-compose.yml` of:
```
- SPLUNK_APPS_URL=/tmp/app.tar.gz
```
(that env var can be a CSV of local and remote URL apps)

**Comment by nwang92** [comment] 2019-11-07 01:06
The example under "Volume-mount app directory" still works for me using `splunk/splunk:8.0` - although it's important to point out that's mounting the untarred app directly into `/opt/splunk/etc/apps/`.

The example above should also be fine - although you may need to use `COPY --chown` if you run into permissions problems.

**Comment by kuroiokami** [comment] 2019-11-07 16:53
So here is what happens

1. Compose up, Playbook completes without any failures
2. Try to go to splunk login page and get the horse oops page
3. Looking in the volume mounted directory only learned and search directories are created.

Looking at the logs via docker logs doesn't actually show any failure in any of the ansible task.

Recap for one that doesn't mount correctly

> Thursday 07 November 2019  16:42:18 +0000 
> (0:00:00.030)       0:00:24.345 ***** 
> =============================================================================== 
> splunk_common : Start Splunk via cli ----------------------------------- 14.79s
> splunk_common : Update Splunk directory owner --------------------------- 3.02s
> splunk_common : Test basic https endpoint ------------------------------- 1.18s
> Gathering Facts --------------------------------------------------------- 0.84s
> splunk_common : Wait for port 8089 to become open ----------------------- 0.71s
> splunk_common : Start Splunk via service -------------------------------- 0.35s
> splunk_common : Update /opt/splunk/etc ---------------------------------- 0.31s
> splunk_common : Check for existing installation ------------------------- 0.31s
> splunk_common : Find manifests ------------------------------------------ 0.31s
> splunk_standalone : Check for required restarts ------------------------- 0.31s
> splunk_common : include_tasks ------------------------------------------- 0.14s
> splunk_common : Check if we are in a docker ----------------------------- 0.14s
> splunk_common : Check for existing splunk secret ------------------------ 0.14s
> splunk_common : Check if /sbin/updateetc.sh exists ---------------------- 0.14s
> Provision role ---------------------------------------------------------- 0.11s
> splunk_standalone : include_tasks --------------------------------------- 0.08s
> splunk_common : include_tasks ------------------------------------------- 0.07s
> splunk_common : include_tasks ------------------------------------------- 0.06s
> splunk_common : include_tasks ------------------------------------------- 0.06s
> splunk_common : include_tasks ------------------------------------------- 0.06s
> 

Recap for one that does mount correctly

> Thursday 07 November 2019  16:48:30 +0000 (0:00:00.022)       0:01:51.324 ***** 
> =============================================================================== 
> splunk_common : Start Splunk via cli ----------------------------------- 39.06s
> splunk_common : Update Splunk directory owner -------------------------- 24.49s
> splunk_common : Enable the Splunk-to-Splunk port ----------------------- 22.37s
> splunk_common : Update /opt/splunk/etc --------------------------------- 15.52s
> splunk_common : Test basic https endpoint ------------------------------- 2.22s
> Gathering Facts --------------------------------------------------------- 1.62s
> splunk_common : Hash the password --------------------------------------- 0.97s
> splunk_common : Check for existing installation ------------------------- 0.55s
> splunk_common : Check if /sbin/updateetc.sh exists ---------------------- 0.46s
> splunk_common : Check if we are in a docker ----------------------------- 0.45s
> splunk_common : Create .ui_login ---------------------------------------- 0.32s
> splunk_common : Generate user-seed.conf --------------------------------- 0.29s
> splunk_common : Wait for port 8089 to become open ----------------------- 0.22s
> splunk_common : Find manifests ------------------------------------------ 0.22s
> splunk_standalone : Check for required restarts ------------------------- 0.19s
> splunk_common : include_tasks ------------------------------------------- 0.11s
> splunk_common : Remove user-seed.conf ----------------------------------- 0.11s
> splunk_common : Check for existing splunk secret ------------------------ 0.10s
> Provision role ---------------------------------------------------------- 0.09s
> splunk_common : include_tasks ------------------------------------------- 0.08s

**Comment by nwang92** [comment] 2019-11-07 17:44
Ah - I'm wondering if there's some discrepancies between how volumes are mounted in the `docker run` vs. `docker-compose` commands then.

In your docker-compose.yml, have you tried changing
```
volumes: 
  - /path/to/app:/opt/splunk/etc/apps/
```
to
```
volumes: 
  - /path/to/app:/opt/splunk/etc/apps/<app-name>
```

I'm thinking what's happening is you're overriding everything in `/opt/splunk/etc/apps` with your original configuration which will have undesired outcomes such as getting those 500s.

**Comment by kuroiokami** [comment] 2019-11-07 18:31
The even stranger thing is... there are sometimes it just works????? I just tried it twice.. First time detecting everything correctly and starting up fine. Second time it was even worse than the other failed instance as the only folder created on startup was learned. 

At this point I'm just going to stick with a standard docker run to get past this issue but will hopefully figure out what is wrong eventually. 

One sidetrack question, do you happen to know how to increase the file system size in the docker image or if there is a particular mapping that would do that? Just getting our standard set of TAs installed gives me a disk space issue in splunk docker.

**Comment by nwang92** [comment] 2019-11-07 21:53
That's likely a limitation on the docker host itself. If you're using Docker for Mac, I think there's something in the settings to configure the disk image size. If you're running on top of Linux, you'll want to add some mount/increase the storage space available at `/var/lib/docker`. 

Another helpful tip is to run `docker volume prune` or `docker image prune` or `docker system prune` periodically to wipe away stale volumes/image layers to free up space on the host running the Docker daemon.

**Comment by nwang92** [comment] 2019-11-08 23:10
Closing this since I'm not quite sure what the exact issue here is, but it seems intermittent and not reliably reproducible. If you're still having issues, I'm happy to continue the discussion either here or through the public Slack channel though!

**Closed as completed by nwang92** 2019-11-08 23:10 UTC
