### ISSUE TITLE
Error after upgrading splunk inside container

### ISSUE THREAD

**Issue by jacauc** [splunk/docker-splunk#400] opened 2020-07-23 14:34 UTC
If I upgrade the splunk version installed in the container, it runs perfectly well, but after I stop and restart the entire container, I get

```
This browser is not supported by Splunk.
Please refer to the list of Supported Browsers.
```

even though Splunk is running in the background.

**Comment by nwang92** [comment] 2020-07-23 17:04
This seems to be caused by a [missing js file](https://community.splunk.com/t5/Archive/quot-This-browser-is-not-supported-by-Splunk-quot/td-p/360742), but I'm not quite certain how that could have occurred.

How are you performing the upgrade? What version are you upgrading from/to?

**Comment by jacauc** [comment] 2020-07-23 21:37
It's actually been bugging me for a while. Every time I upgrade. Originally from 7.x to 7.y, but the latest was 8.01 to 8.05.

I upgraded using the wget to pull the Deb package and then did dpkg -i to run through the upgrade sequence. After restarting splunk all is good, until I restart the container.

**Comment by jacauc** [comment] 2020-07-23 21:40
If I recall correctly, last time I tried to delete the entire /opt/splunk/var folder, ran setup again and it was good. But after restarting container it breaks again

**Comment by nwang92** [comment] 2020-07-31 16:19
I believe the upgrade process we recommend is to bump the image version you're using. Something like:
```
# First time launch
SPLUNK_IMAGE=splunk/splunk:8.0.1 docker-compose up -d
# Upgrading
SPLUNK_IMAGE=splunk/splunk:8.0.2 docker-compose up -d
```

There's nothing wrong with the deb approach, but it's kind of treating the container as a VM. Also, upon restart, the entrypoint may try to "reset" the container back to the built-in version which may be the cause of your complications.

**Comment by jacauc** [comment] 2020-08-05 04:58
Hi @nwang92 

Sorry for the delayed response, I missed this reply.
Where would I bump this image version? Is that an environment variable?

**Comment by jacauc** [comment] 2020-08-05 05:03
Also, I understand that I am treating the container as a VM, and this is probably not ideal. Is there any other means of upgrading the container automatically upon boot or another way?

**Comment by nwang92** [comment] 2020-08-05 21:37
You'd have to change the image itself. I don't think there's a way to do it natively from the `docker run` CLI - maybe if you go through the trouble of using named volumes like:
```
## Launch splunk for the 1st time using named volumes
$ docker run -d -P --name splunk -v splunk-etc:/opt/splunk/etc -v splunk-var:/opt/splunk/var -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld splunk/splunk:8.0.1

## Stop and remove the container
$ docker stop splunk
$ docker rm splunk

## Start another splunk using a newer version, using existing data
$ docker run -d -P --name splunk -v splunk-etc:/opt/splunk/etc -v splunk-var:/opt/splunk/var -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=helloworld splunk/splunk:8.0.2
```

Alternatively, you can probably reference the compose file here to achieve the same thing as the above, but through the `docker-compose` CLI:
 https://github.com/splunk/docker-splunk/blob/develop/test_scenarios/1so_namedvolumes_upgrade.yaml
```
# First time launch
SPLUNK_PASSWORD=helloworld SPLUNK_IMAGE=splunk/splunk:8.0.1 docker-compose -f 1so_namedvolumes_upgrade.yaml up -d
# Upgrading
SPLUNK_PASSWORD=helloworld SPLUNK_IMAGE=splunk/splunk:8.0.2 docker-compose -f 1so_namedvolumes_upgrade.yaml up -d
```

**Comment by jacauc** [comment] 2020-08-06 05:35
Thank you very much! I'm not very well versed when it comes to Docker compose as I simply use the containers directly on my synology NAS. I will have to go dig to see how I can change this from the Synology SSH CLI.

Little more intricate than I thought honestly :)

**Comment by nwang92** [comment] 2020-08-07 17:52
No problem, our approach is to make the Splunk container experience feel more like a microservice so that it plays nice with orchestration systems like Swarm/Kubernetes. But those goals may not always jive with smaller-scale deployments - luckily I believe there's ways to achieve what you're after, although with a little bit more YAML unfortunately :P

I'm going to close this ticket, but feel free to comment or re-open if you're still hitting problems.

**Closed as completed by nwang92** 2020-08-07 17:52 UTC
