### ISSUE TITLE
Not able to install java

### ISSUE THREAD

**Issue by jasonhue8183** [splunk/docker-splunk#167] opened 2019-04-05 02:18 UTC
Hi ,

I have problem to install java with below docker run command :

docker run -d -p 8000:8000 -p 8089:8089 -e JAVA_VERSION=openjdk:8  -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=P@ssw0rd123456  splunk/splunk:7.2.5.1

![failed to install java](https://user-images.githubusercontent.com/8756745/55599799-f5f42680-578b-11e9-8380-2bfba5c52d14.png)

Appreciate for any advice.
Thanks
Jason

**Comment by nwang92** [comment] 2019-04-05 17:53
Not able to reproduce this:
```
$ docker run -d -p 8000:8000 -p 8089:8089 -e JAVA_VERSION=openjdk:8 -e SPLUNK_START_ARGS=--accept-license -e SPLUNK_PASSWORD=P@ssw0rd123456 splunk/splunk:7.2.5.1
8a89ef9ebbba084745ba1ac246c71e3094fc4efce259dc813500744f821a96be
$ docker exec -it 8a89ef9ebbba java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```

Could you provide some more details about the Docker version, environment, etc. you're running in?

**Comment by jasonhue8183** [comment] 2019-04-08 02:34
Hi @nwang92 ,

My environment as below 
- Docker version 18.06.1-ce-win73
- Windows 10 Enterprise
- behind company proxy

Appreciate for any advice
Best Regards
Jason

**Comment by arctan5x** [comment] 2019-04-08 19:34
@jasonhue8183 We are currently not supporting Java installation on Windows through Ansible. We currently support Java in a debian based container.

**Comment by jasonhue8183** [comment] 2019-04-09 04:03
Hi @arctan5x ,

Sorry i kinda confused. You mean only support Java in a debian based **host** ?

Appreciate for any advice
Best Regards
Jason

**Comment by arctan5x** [comment] 2019-04-09 17:11
@jasonhue8183 Debian container.

**Comment by jasonhue8183** [comment] 2019-04-10 01:50
Hi @arctan5x ,

we are using docker for windows but using linux container.
![image](https://user-images.githubusercontent.com/8756745/55845826-fae31c80-5b75-11e9-8f77-c628c4719c55.png)

Appreciate for any advice
Best Regards
Jason

**Comment by nwang92** [comment] 2019-04-12 18:15
That's interesting - I don't think we've tested this thoroughly on the Docker for Windows workflow, although it's surprising that there are large discrepancies like this. Are you able to start Splunk on Docker for Windows without the `JAVA_VERSION` option?

**Comment by jasonhue8183** [comment] 2019-04-12 21:53
Hi @nwang92,

Yes, it's working fine without JAVA_VERSION option.

Jason

**Comment by jasonhue8183** [comment] 2019-05-21 02:19
Hi @nwang92,

Any fix for this ?

Jason

**Comment by nwang92** [comment] 2019-05-22 01:15
Sorry dropped the ball on this - I'll spin up a Windows instances to test this out tonight and get back to you.

**Comment by nwang92** [comment] 2019-05-22 19:07
K quick update, I'm trying to procure some Windows 10 environment. It seems like running Linux containers on Windows requires Hyper-V enabled, which isn't supported through our cloud provider. 

Looking through our java setup plays, I wonder if this is some underlying problem with how linux containers run on Windows. Can you run the following `docker run` command in your environment and report what you see?
```
$ docker run -it debian:stretch-slim bash -c 'mkdir -p /usr/share/man/man1; apt-get update; apt-get install -y openjdk-8-jre-headless; /usr/bin/java -version'
...
Setting up openjdk-8-jre-headless:amd64 (8u212-b01-1~deb9u1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/clhsdb to provide /usr/bin/clhsdb (clhsdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/hsdb to provide /usr/bin/hsdb (hsdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/orbd to provide /usr/bin/orbd (orbd) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/servertool to provide /usr/bin/servertool (servertool) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Processing triggers for libc-bin (2.24-11+deb9u4) ...
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```

The above is essentially all our Splunk image tries to do (same base image, same commands). On my macbook, I'm seeing the command return successfully but I'm guessing in your environment, it shouldn't? If it does error out, could you also send me a snippet of the output?

**Comment by jasonhue8183** [comment] 2019-05-24 05:39
Hi @nwang92,

Thank you for the update, I had the error below. Something not right.

![splunk](https://user-images.githubusercontent.com/8756745/58305012-2d489080-7e29-11e9-94fb-e5e166a82543.png)

Appreciate for any advice
Best Regards
Jason

**Comment by nwang92** [comment] 2019-05-28 22:04
My guess is that command prompt/powershell threw up on the input given. I wonder if changing the command/args might make it happier?

Maybe something like one of the following:
```
# Double-quotes
$ ... bash -c "mkdir -p /usr/share/man/man1; apt-get update; apt-get install -y openjdk-8-jre-headless; /usr/bin/java -version"

# Full path to binary, everything in quotes
$ ... "/bin/bash -c 'mkdir -p /usr/share/man/man1; apt-get update; apt-get install -y openjdk-8-jre-headless; /usr/bin/java -version'"

# Removing the -p option
$ ... "/bin/bash -c 'mkdir /usr/share/man/man1; apt-get update; apt-get install -y openjdk-8-jre-headless; /usr/bin/java -version'"
```

Very strange that it doesn't work though. I'm still waiting on my Windows 10 box to get provisioned, but it seems like there's some disparity between running linux containers on linux vs. the promise of running linux containers on Windows :(

**Comment by arctan5x** [comment] 2019-08-20 00:25
Closing this. We have Java 9 Support on windows actually so feel free to check it out.

**Closed as completed by arctan5x** 2019-08-20 00:25 UTC
