### ISSUE TITLE
handshake operation timed out

### ISSUE THREAD

**Issue by justinrush** [splunk/docker-splunk#296] opened 2019-12-17 19:52 UTC
I'm running this on this on kubernetes v1.14.8 in a stateful set I built out.  If its important, the pod contains multiple containers, one of which is the 7.3.3 splunk container.  The other two are a syslog-ng and a logrotate container.  On first deployment, everything works fine.  If I kill the pod and let it restart, it sometimes gets into a state while running "test basic https endpoint" (that gets ignored), but then it fails on "disable indexing on current node" with connection reset by peer.  Sometimes it will eventually recover from this as it is endless killed and restarted, but most times I need to kill the pod and the PVCs so that it will generate a new splunk instance.

I'm guessing the service is just taking a bit longer than ancible thinks it should to come up and thus killing the PVCs fixes it because it will have a longer start up time as ancible is starting a full run on a fresh "image".

Is there a sleep that needs to get added somewhere?  or like retry on failure?

full logs are attached, specific task output that fails is below.
```
TASK [splunk_heavy_forwarder : Disable indexing on the current node] ***********
fatal: [localhost]: FAILED! => {
"changed": false,
"content": "",
"elapsed": 0,
"redirected": false,
"status": -1,
"url": "http://127.0.0.1:8089/servicesNS/nobody/system/configs/conf-outputs"
}
MSG:
Status code was -1 and not [201, 409]: Connection failure: [Errno 104] Connection reset by peer
```
[splunk_container_logs.txt](https://github.com/splunk/docker-splunk/files/3975171/splunk_container_logs.txt)

**Comment by bb03** [comment] 2019-12-17 20:02
@justinrush 
+ @nwang92 
 A timeout and/or a few retries here make sense, given what you've described.  Can you make a local change and let us know if it works for your environment?  Just something like
```
retries: 5
delay: 30
```
to that task and let us know if it works for you.

**Comment by justinrush** [comment] 2019-12-17 20:20
> @justinrush
> 
> * @nwang92
>   A timeout and/or a few retries here make sense, given what you've described.  Can you make a local change and let us know if it works for your environment?  Just something like
> 
> ```
> retries: 5
> delay: 30
> ```
> 
> to that task and let us know if it works for you.

What file do I make that change in?  Sorry, don't know ancible at all.

**Comment by bb03** [comment] 2019-12-17 20:36
It's in roles/splunk-common/tasks/enable_forwarding.yml . Look the the stanza at the bottom and add the last two lines (after no_log) with the same indentation level
```
# NOTE: If this task is called or used, it will disable all local indexing!
- name: Disable indexing on the current node
 <snip>
  no_log: "{{ hide_password }}"
  retries: 10 
  delay: 20
```

**Comment by justinrush** [comment] 2019-12-17 22:05
That seemed like it worked for one pod, but another one I tested with just continues to restart.  I tried upping the delay to 60 seconds.  Is there a specific log file that may contain useful information?  I can exec into the container and tail the log until it crashes.

**Comment by justinrush** [comment] 2019-12-19 15:51
is there a variable i can set to do this or some tunable?  including that file as a configmap is a bit ugly.  I either have to escape a bunch of stuff or include it as a file because it is itself a GO template.  While helm and k8s seems OK with it, rancher seems to be unable to load my statefulset when trying to get info on that configmap.

**Comment by justinrush** [comment] 2019-12-19 16:08
on further testing, it doesn't seem that changing these values is making a difference.  Still seems to randomly run into the error

**Comment by bb03** [comment] 2019-12-19 19:59
@justinrush Check out the ansible.log in /opt/container-artifact That should contain the setup log.  The other splunk specific logs would be in /opt/splunk/var/log/splunk or /opt/splunkforwarder/var/log/splunk
Let us know what you find and we'll be happy to assist.

**Comment by justinrush** [comment] 2019-12-23 16:54
Not seeing anything standing out as an issue.  it looks like it starts up fine.  For testing purposes, should I modify a file to have it ignore failures and see if the service is actually still healthy?  splunkd log section attached as well as the artifact log.
[splunk_ancible.log](https://github.com/splunk/docker-splunk/files/3995639/splunk_ancible.log)
[splunkd.log](https://github.com/splunk/docker-splunk/files/3995640/splunkd.log)

**Comment by nwang92** [comment] 2020-04-01 17:49
Sorry this kinda fell off my radar. I think the problem is actually in "test basic https endpoint". Given the above output I'm noticing:
```
...
"url": "http://127.0.0.1:8089/servicesNS/nobody/system/configs/conf-outputs"
}
MSG:
Status code was -1 and not [201, 409]: Connection failure: [Errno 104] Connection reset by peer
```

It looks like it's attempting to hit the splunkd management port on 8089 over HTTP and not HTTPS. Assuming you haven't disabled SSL on port 8089, this *should* always be using HTTPS, at least by default.

A while ago I [added retries over this section](https://github.com/splunk/splunk-ansible/commit/2e5d07039b4b931556bb87a8b7c361bb5dd60e33#diff-127d43f479d25d8f0be2e3b68f0abd2a), so I'm assuming that with the last few sets of images you should've seen this problem mitigated. I'm going to close this issue out, but please feel free to re-open it or continue the comment thread if you continue to see problems!

**Closed as completed by nwang92** 2020-04-01 17:49 UTC

**Comment by timdonovanuk** [comment] 2020-05-26 15:29
I'm getting `FAILED - RETRYING: Test basic https endpoint (60 retries left).` on a first deploy of splunk. I've got about the most basic setup, and just copied the docker run commands from https://github.com/splunk/docker-splunk.

Unfortunately it doesn't actually even show what endpoint it's trying to reach, and because the container doesn't actually start I cannot log into it to see whats going on.

Edit: I was wrapping the password in "" and apparently that didn't parse right. Working now!
